services:   
  frontend:
    restart: always
    command : npm start
    container_name: react
    build:
      context: ./ra-react-app/
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"    
    stdin_open: true
